### ISSUE TITLE
Error trying to install http-server on nodejs

### ISSUE THREAD

**Issue by ChrisMuster** [angular/angular-phonecat#398] opened 2017-02-07 13:10 UTC
Hello. First a warning: I know less than nothing about nodejs or most command line applications, so everything I have tried to google on this issue has led me to what looks to my eyes as gobbledegook and nonsense, although I'm sure there is some solution that escapes me. What this means is you may have to be exceptionally simplistic in your explanations.
While trying to download and set up the angular-phonecat project, I followed the instructions to download nodejs, and then the instructions to change directory to angular-phonecat, then when it says run the line **npm start** i get the following:

```
> angular-phonecat@0.0.0 start C:\Users\Chris Muster\angular-phonecat
> http-server ./app -a localhost -p 8000 -c-1

events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at Server._listen2 (net.js:1248:19)
    at listen (net.js:1297:10)
    at doListening (net.js:1396:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server ./app -a localhost -p 8000 -c-1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server ./app -a localhost -p 8000 -c-1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server ./app -a localhost -p 8000 -c-1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Chris Muster\angular-phonecat\npm-debug.log


The log in the last line has this info:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-phonecat@0.0.0~prestart: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Chris Muster\angular-phonecat\node_modules\.bin;C:\Users\Chris Muster\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\Ruby23\bin;C:\Users\Chris Muster\AppData\Local\Microsoft\WindowsApps;C:\Users\Chris Muster\AppData\Roaming\npm
8 verbose lifecycle angular-phonecat@0.0.0~prestart: CWD: C:\Users\Chris Muster\angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~prestart: Args: [ '/d /s /c', 'npm install' ]
10 silly lifecycle angular-phonecat@0.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~start: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Chris Muster\angular-phonecat\node_modules\.bin;C:\Users\Chris Muster\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\Ruby23\bin;C:\Users\Chris Muster\AppData\Local\Microsoft\WindowsApps;C:\Users\Chris Muster\AppData\Roaming\npm
14 verbose lifecycle angular-phonecat@0.0.0~start: CWD: C:\Users\Chris Muster\angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~start: Args: [ '/d /s /c', 'http-server ./app -a localhost -p 8000 -c-1' ]
16 silly lifecycle angular-phonecat@0.0.0~start: Returned: code: 1  signal: null
17 info lifecycle angular-phonecat@0.0.0~start: Failed to exec start script
18 verbose stack Error: angular-phonecat@0.0.0 start: `http-server ./app -a localhost -p 8000 -c-1`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:192:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:192:7)
18 verbose stack     at maybeClose (internal/child_process.js:890:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd C:\Users\Chris Muster\angular-phonecat
21 error Windows_NT 10.0.14393
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
23 error node v7.5.0
24 error npm  v4.1.2
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 start: `http-server ./app -a localhost -p 8000 -c-1`
26 error Exit status 1
27 error Failed at the angular-phonecat@0.0.0 start script 'http-server ./app -a localhost -p 8000 -c-1'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     http-server ./app -a localhost -p 8000 -c-1
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

I have no idea what any of this means and I'm tearing my hair out trying to understand, any help would be much appreciated.

**Comment by ChrisMuster** [comment] 2017-02-07 13:12
I have no idea why some of the lines above have been crossed out, they weren't in the original copy.

**Comment by gkalpak** [comment] 2017-02-07 13:42
They are not crossed out now :wink:

The error means that (for whatever reason) you can't access port 8000. One common reason is that some other process is already using it. Either try changing the port (in `package.json`) or try to find out if who might be using the port, by following thr instructions [here][1].

[1]: http://www.codingdefined.com/2015/09/solved-cannot-start-server-at-00008080.html

**Comment by ChrisMuster** [comment] 2017-02-07 14:07
Thanks for the reply.
I don't know anything about package.json.
I had a look at your link, and tried to install node-inspector (whatever that is, I still don't know), and got another error, maybe I'm trying to install it in the wrong place?
C:\Users\Chris Muster\angular-phonecat>npm install -g node-inspector

> v8-debug@0.7.7 preinstall C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\.staging\v8-debug-1bb640cd
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\.staging\v8-profiler-fbc145bb
> node -e 'process.exit(0)'

C:\Users\Chris Muster\AppData\Roaming\npm\node-debug -> C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\bin\node-debug.js
C:\Users\Chris Muster\AppData\Roaming\npm\node-inspector -> C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\bin\inspector.js

> v8-debug@0.7.7 install C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.5.0 (node-v51 ABI) (falling back to source compile with node-gyp)

C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node" --module_name=debug "--module_path=C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64" )  else (node "" configure --fallback-to-build "--module=C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node" --module_name=debug "--module_path=C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64" )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Chris Muster\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v51-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\Chris Muster\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v51-win32-x64"
gyp ERR! cwd C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chris Muster\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v7.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Chris Muster\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64' (1)
npm WARN Error: EPERM: operation not permitted, rmdir 'C:\Users\Chris Muster\AppData\Roaming\npm\node_modules'
npm WARN  { Error: EPERM: operation not permitted, rmdir 'C:\Users\Chris Muster\AppData\Roaming\npm\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'rmdir',
npm WARN   path: 'C:\\Users\\Chris Muster\\AppData\\Roaming\\npm\\node_modules' }
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Chris Muster\angular-phonecat\npm-debug.log



When I looked at what was using port 8000, this is what I got:

C:\Users\Chris Muster\angular-phonecat>netstat -ano | find "8000"
  TCP    0.0.0.0:8000           0.0.0.0:0              LISTENING       4
  TCP    [::]:8000              [::]:0                 LISTENING       4


Any more ideas? It seems like every time I try to fix something, I need something else to fix the fix, and then something else to fix that...which leads to me becoming very confused.

**Comment by gkalpak** [comment] 2017-02-07 14:18
You didn't have to install `node-inspector` :smiley: Just run `netstat -ano | find "8000"`.
According to the output you got from running this command, it seems that a process (with process ID 4) is using the port. That is why you can't use it from `angular-phonecat`.

You can either terminate the process with PID 4 (you can find it by opening th Windows Task Manager (Ctrl+Shift+Esc) and looking at the PID column of a tab called "Details" or something like this), or you can change the port used by phonecat (but it is more complicated, because you need to edit more than one files and the changes will be lost the next time you checkout another step).

So, try to locate the process with PID 4 in the Task Manager and terminate it.

**Comment by ChrisMuster** [comment] 2017-02-07 14:24
PID 4 was being used by the SYSTEM, with a description of NT Kernel & System. It would not allow it to be terminated.
Assuming at the moment that NT Kernel is something I should not mess with, what should I do next? If I have to change ports, how? Thank you.

**Comment by gkalpak** [comment] 2017-02-07 14:50
Yeah, you should probably not terminate SYSTEM stuff. It is weird why it would be using port 8000. I haven't seen that before. Apparently it can be a bunch of stuff, as explained [here][1] and [there][2].

##
I am afraid I can't help more on that remotely. So, back to plan B: Change the ports used by the tutorial

You need to replace 8000 with another value (e.g. 9000) in the following files:

- package.json
- e2e-tests/protractor.conf.js

(The problem is that whenever you checkout a new step, your changes might be overwritten, so you will need to aply them again 😞)

[1]: http://stackoverflow.com/questions/12492025/windows-8-nt-kernel-and-system-using-port-80
[2]: http://superuser.com/questions/394288/port-8000-locked-by-an-application

**Comment by ChrisMuster** [comment] 2017-02-07 15:53
Ok, after searching for a long time and finding nothing, I finally realised that the package.json and the e2e-tests files would be in the angular-phonecat directory (duh) and that the filepath to those files was staring at me from the cmd line the whole time...!
I found both files and changed the port number in them, then saved. Ran npm start from the angular-phonecat dir again, and this time it said it was starting up the server, with the new port number I chose.
So now I am able to try the rest of this project and see if I can get it going without too many more issues!
Thank you gkalpak for the help. 
Just for the sake of not wanting to run into any other errors quickly, what did you mean by the line:
"(The problem is that whenever you checkout a new step, your changes might be overwritten, so you will need to apply them again 😞)"?
I don't want to be surprised by anything else! Thanks.

**Comment by gkalpak** [comment] 2017-02-07 16:16
As you follow each step of the tutorial, you can run `git checkout -f step-X` to reset your workspace at step `X`. This command will essentially make all the files in your local `angular-phonecat` directory reflect the changs that were made for step `X`, so that you can see the actual files and can play with them, run the server and browse the website, run the unit and e2e tests etc (if it doesn't make sense, it will hopefully do down the way as you proceed with the tutorial).

Now, the problem is that each time you run `git checkout -f step-X`, the changes you have made to the ports will be ovrwritten (i.e. the port will be reset to 8000). So, after you run that command, you need to go into the two files (`package.json` and `e2e-tests/protractor.conf.js`) and change the port number again.

##
Since you were able to solve the problem (or at least work around it), I will close the issue, but feel free to continue the discussion below, if you need more help.

**Closed by gkalpak** 2017-02-07 16:16 UTC
