### ISSUE TITLE
Unknown SSL protocal error in connection to github.com:443

### ISSUE THREAD

**Issue by xu10081008** [angular/angular-phonecat#212] opened 2014-11-06 04:29 UTC
It's my first useing git;I want to clone "angular-phonecat",so i use "git clone https://github.com/angular/angular-phonecat.git",but it throws an exception as the title.
I need your help

**Comment by xu10081008** [comment] 2015-02-05 06:08
I'm sorry for long time to answer you and through a long time ,I can't remember how to fix it. 
the step  to do is:
Personal settings——> SSH Keys ——> Add ssh key
I hope that can help you

**Comment by alexandre-mbm** [comment] 2015-03-27 04:23
Update the system packages.
On Arch Linux: `sudo pacman -Syu` (here this worked)
On Ubuntu: `sudo apt-get update && sudo apt-get upgrade`

**Comment by justinTomas** [comment] 2015-05-28 03:00
I have same question as the tittle when i use github for windows.
How can i resolve it?

**Comment by xu10081008** [comment] 2015-06-02 03:37
1. sign in the GitHub
2. enter the interface: "Personal settings", then click "SSH Keys"
3. please confirm whether you have put the 'id_rsa.pub' that generated by the command 'ssh-keygen -t rsa ' on windows into github
4. if not,click 'Add SSH key' and put the 'id_rsa.pub' into it.
I hope it works for you,and if it works please replay

**Comment by justinTomas** [comment] 2015-06-17 04:05
I did what you said, but it also gave a same hint

**Comment by petebacondarwin** [comment] 2015-06-29 12:52
It sounds like you are having problems with your internet connection setup.
Perhaps you could try using the `git://` form of the url instead: git@github.com:angular/angular-phonecat.git

**Comment by lealcy** [comment] 2015-08-14 18:16
Hi, I'm having the follow issue:

    C:\Users\lealcybj\Documents\GitHub> git clone git@github.com:lealcy/Edge.git
    Cloning into 'Edge'...
    ssh_exchange_identification: read: Connection reset by peer
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    C:\Users\lealcybj\Documents\GitHub> git clone https://github.com/lealcy/Edge.git
    Cloning into 'Edge'...
    fatal: unable to access 'https://github.com/lealcy/Edge.git/': Unknown SSL protocol error in connection to github.com:443
    C:\Users\lealcybj\Documents\GitHub>

It started after I upgraded my windows from 7 to 10. I'm behind an ISA proxy, but in Windows 7 it worked flawlessly.

**Comment by gfaust-qb** [comment] 2015-08-25 10:32
Just try to update your Git-Version. Got problems today, updated git (used v1.9 before) and there are no problems left.

**Comment by 92arpitgoyal** [comment] 2015-08-25 12:28
Updating git (from v1.9) and now there are no problems left.

**Comment by sidlors** [comment] 2015-11-10 21:55
WTF ??

**Comment by Almirhabib** [comment] 2016-02-01 14:14
i am also having the following issue i try many time but again and again face that problem not good any one tell me right reason

**Comment by lealcy** [comment] 2016-02-02 15:59
Still having issues:

2016-02-02 13:56:06.9767|WARN|thread: 1|StandardUserErrors|Showing user error Please check your log file for more details, or email support if you are still having problems.
GitHub.IO.ProcessException: 13:56:03.506154 git.c:348               trace: built-in: git 'clone' '--progress' '--recursive' '--' 'https://github.com/lealcy/sharp2d.git' 'sharp2d'
13:56:03.612224 run-command.c:335       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/lealcy/sharp2d.git'
Cloning into 'sharp2d'...
* Couldn't find host github.com in the _netrc file; using defaults
* timeout on name lookup is not supported
*   Trying 192.30.252.130...
* Connected to github.com (192.30.252.130) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Users\lealcybj\AppData\Local\GitHub\PortableGit_c7e0cbde92ba565cb218a521411d0e854079a28c\mingw32/ssl/certs/ca-bundle-ghfw.crt
  CApath: none
* Unknown SSL protocol error in connection to github.com:443 
* Closing connection 0
fatal: unable to access 'https://github.com/lealcy/sharp2d.git/': Unknown SSL protocol error in connection to github.com:443

**Comment by zzeniou86** [comment] 2016-02-21 23:49
If you are in hurry, the easiest way is https://guides.github.com/activities/hello-world/ (you will need to copy/paste the solution from your local files to your github editor).

Although if you do want to keep going on with the courses, you need to understand github and git.

**Comment by gkalpak** [comment] 2016-04-05 11:30
Closing as it doesn't seem related to the tutorial.

**Closed by gkalpak** 2016-04-05 11:30 UTC

**Comment by svscorp** [comment] 2016-08-24 16:24
I wonder, did you fix the issue @xu10081008 @lealcy  ?

**Comment by qyffWJ** [comment] 2016-11-14 07:31
what the boom

**Comment by lealcy** [comment] 2016-12-07 18:20
@svscorp Yeah. Installed cntlm to use the AD based proxy authentication. Works like a charm now.

**Comment by shadabacc406** [comment] 2017-04-12 22:56
Hi,....Please help me with this issue..

 > C:\Projects\GIT\Git\mingw64\bin\git.exe fetch --tags --progress https://github.com/shadabacc406/test.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "C:\Projects\GIT\Git\mingw64\bin\git.exe fetch --tags --progress https://github.com/shadabacc406/test.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/shadabacc406/test.git/': Unknown SSL protocol error in connection to github.com:443 

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1799)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1525)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:65)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:316)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:513)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1061)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1101)

**Comment by mmmshebli** [comment] 2017-08-29 15:02
I have the same issue which made me hit my head in the wall, I am behind a corporate proxy, it only worked when I removed the http.proxy from github config and added sslVerify = false

**Comment by thonglm1608** [comment] 2017-09-25 08:12
Hi guys,
Please help me with this issue:

trace: built-in: git 'clone' 'https://ProjectURL'
Cloning into ...
 run-command.c:626       trace: run_command: 'remote-https' 'origin' 'https://ProjectURL'
 trace: exec: 'git-remote-https' 'origin' 'https://ProjectURL'
trace: run_command: 'git-remote-https' 'origin' 'https://ProjectURL'
* Couldn't find host svc...(host name) in the _netrc file; using defaults
* timeout on name lookup is not supported
*   Trying 1x.1x.1x.5x...
* TCP_NODELAY set
* Connected to svc.tek-experts.com ( 1x.1x.1x.5x) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Users\thong.luyen-minh\AppData\Local\Atlassian\SourceTree\git_local\mingw32/ssl/certs/ca-bundle.crt
  CApath: none
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to svc.tek-experts.com:443
* stopped the pause stream!
* Closing connection 0
fatal: unable to access 'https://ProjectURL': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to svc.tek-experts.com:443

Thanks you very much.

**Comment by gkalpak** [comment] 2017-09-25 08:40
What command have you used to do the cloning? Have you followed the instructions from [here][1]?

[1]: https://docs.angularjs.org/tutorial

**Comment by thonglm1608** [comment] 2017-09-25 08:47
@gkalpak: This is my command: GIT_CURL_VERBOSE=1 GIT_TRACE=1 git clone https://PrtojectURL.
I've been try with another command: git pull origin develop or git push origin develop  and  the error message alway is: "fatal: unable to access 'https://ProjectURL': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to svc...com:443"

**Comment by gkalpak** [comment] 2017-09-25 09:06
This doesn't seem like a valid URL. If you are trying to clone the tutorial, please follow the instructions [here][1].

[1]: https://docs.angularjs.org/tutorial

**Comment by thonglm1608** [comment] 2017-09-25 09:11
@gkalpak : This is private url so i can't show it. i'm sure use a valid url.
My english is not good, if you don't understand please tell me.:(

**Comment by gkalpak** [comment] 2017-09-25 09:47
It sounds like an issue in your network setting then (maybe a proxy or a firewall blocking access to the remote repository), as indicated by this line:

> OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to <URL>:<PORT>

In any case, this is not related to the Angular tutorial, so nothing we could help you with 😕

**Comment by macatlan** [comment] 2018-02-23 00:34
I have the same problem, Do you know how I could fix it?! 

# git pull origin mybranch
fatal: unable to access 'https://usuario@github.com/inite/upstream.git/': SSL connect error

Go info about my instance.
 
# curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.18 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 
# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
# git --version
git version 2.5.0

Thanks a lot!!!

**Comment by smartree** [comment] 2018-03-08 16:59
Network env config concerning, but just try change:
git clone https://github.com/angular/angular-phonecat.git
from up to down,
git clone git://github.com/angular/angular-phonecat.git
Then go on to find your solution.

**Comment by shegzytom** [comment] 2018-03-15 14:36
Hi, Kindly help with this issue
fatal: unable to access 'https://github.com/OmarElGabry/chat.io.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

**Comment by smartree** [comment] 2018-03-20 07:19
CentOS You can try first:
sudo yum update nss
or plus:
sudo yum update openssh
or plus all related lib:
sudo yum update openssh nss curl libcurl 

Still not work? try:
env GIT_SSL_NO_VERIFY=true git clone https://github.com/Project/Name.git

**Comment by bimalkjha** [comment] 2018-06-19 14:00
@ajiejot The problem is the use of https in the url. You should use `git clone git@github.com:ajiejot/TestGit.git` command after configuring the [SSH Key](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) for your github id. Thanks.

**Comment by mrgoodrich** [comment] 2018-07-20 02:30
It could be different for you, but

`git config --global credential.helper wincred`

worked for me on Windows. It was working before I received this message, fyi.

**Comment by gssarwar** [comment] 2018-08-27 09:59
Hi ,
while i am adding remote git hub repository to IntelliJ IDEA Community Edition 2018.2.2 x64 ide then getting below error 
OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

Kindly help me to resolve it.
Git version is 2.18.0
ide : IntelliJ IDEA Community Edition 2018.2.2 x64

**Comment by amyqian379** [comment] 2018-11-27 03:37
Hello Guys,

could you please help with this issue?

aos-cube version: 0.2.63
Cloning into 'gcc-arm-none-eabi'...
fatal: unable to access 'https://gitee.com/alios-things/gcc-arm-none-eabi-win32.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitee.com:443
Cloning into 'OpenOCD'...
fatal: unable to access 'https://gitee.com/alios-things/openocd-win32.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitee.com:443
Making config file for first time
INFO: Could not find files for the given pattern(s).
build/aos_toolchain_arm-none-eabi.mk:42: *** can not find compiler toolchain, please download "gcc-arm-none-eabi-5_4-2016q3-20160926-win32.zip" from "https://launchpad.net/gcc-arm-embedded/+download" and unzip to C:/Users/mqian/Alios-Things/build/compiler/gcc-arm-none-eabi/Win32 folder.  Stop.

Git version is 2.19.2

**Comment by sjhsjh** [comment] 2019-05-03 03:54
because i am using vpn！！！close vpn will work！

**Comment by venvogs** [comment] 2019-08-06 14:43
Do we have a solution to this yet? I am facing the same problem couldn't find solution over the internet yet. :( 
![image](https://user-images.githubusercontent.com/53437836/62549691-8cb21c00-b82e-11e9-824c-07c38de367ad.png)

**Comment by ROBBTECH** [comment] 2019-11-04 18:59
It worked for me after removing the file causing an error .git/refs/remotes/origin/

**Comment by pythondev0101** [comment] 2020-03-23 05:29
> because i am using vpn！！！close vpn will work！

yes, this is because of vpn

**Comment by webkhushboo** [comment] 2020-06-21 15:46
> Do we have a solution to this yet? I am facing the same problem couldn't find solution over the internet yet. :(
> ![image](https://user-images.githubusercontent.com/53437836/62549691-8cb21c00-b82e-11e9-824c-07c38de367ad.png)

Did you find the solution for this error ? I am not able to fix it.

**Comment by u54256** [comment] 2021-10-15 22:40
@webkhushboo,  your git ID does not have permissions, you need to check your git id permissions. you can use github desktop app.

**Comment by dilansampath** [comment] 2022-03-20 05:06
> 1. sign in the GitHub
> 2. enter the interface: "Personal settings", then click "SSH Keys"
> 3. please confirm whether you have put the 'id_rsa.pub' that generated by the command 'ssh-keygen -t rsa ' on windows into github
> 4. if not,click 'Add SSH key' and put the 'id_rsa.pub' into it.
> 
> I hope it works for you,and if it works please replay

at last this worked. thanks a lot.
