### ISSUE TITLE
run http://localhost:8000/app/ in Chrome, the browser says can not access this site

### ISSUE THREAD

**Issue by zhoubhin** [angular/angular-phonecat#322] opened 2016-04-08 07:38 UTC
I run npm start under branch master and run http://localhost:8000/app/ in Chrome, but the browser says
can not access this site, so anyone else know how to solve this problem? Windows 10 with Node v4.3.0

**Comment by mkalim** [comment] 2016-04-08 11:50
I'm facing a similar problem. Its been two days trying to setup angular environment in Ubuntu :(. I hope you should if you do not face error/warning with npm install and npm start

**Comment by zhoubihn** [comment] 2016-04-08 12:44
@mkalim  About a month ago when i coded under Ubuntu, i also met a problem that no any reactions when i code node -v in Ubuntu terminal although i had installed Node by using "apt-get install"...I will try to solve the problem you say,

**Comment by zhoubihn** [comment] 2016-04-10 10:50
@mkalim  OK, i have solve the problem you said. First of all, you should compile the Node source code, run "npm install" and "npm start" under the /angular-phonecat , then go to http://localhost:8000/app/index.html in browser(i use firefox) , you will see Nothing here yet on the page.(git checkout -f step-0 after compile Node source code)

**Comment by mkalim** [comment] 2016-04-15 06:59
@zhoubhin I think the problem is still there with the way it clones.. I left that phonecat project and started following other tutorials.. npm install works fine..

**Comment by zhoubhin** [comment] 2016-04-15 07:07
@mkalim   aha, i followed another project and faced similar problem…

**Comment by gkalpak** [comment] 2016-04-15 07:35
@zhoubhin, what is the problem you are facing ? I thought you said you were able to navigate to `/app/index.html` and see `Nothing here yet`. So it should be working.

**Comment by zhoubhin** [comment] 2016-04-18 06:41
@gkalpak  I mean i insert "http://localhost:8000/app" into address bar of Chrome that i can not navigate to the /app/index.html under Windows 10, but i can navigate to the `/app/index.html`under Ubuntu successfully...

**Comment by zhoubhin** [comment] 2016-04-18 06:44
@gkalpak  Chrome displays "can not access this site"(Windows 10 Node 4.3.0) while it says "Nothing here yet"(Ubuntu 14.04 Node 4.3.0)

**Comment by zhoubhin** [comment] 2016-04-19 08:41
@gkalpak  Okay, i solve this problem, thanks for your helps.

**Comment by gkalpak** [comment] 2016-04-19 10:37
@zhoubhin, great ! I'm going to close this then, since you made it work for you and there is already a PR for fixing it for everyone.

**Closed by gkalpak** 2016-04-19 10:37 UTC

**Comment by roshankumarlakhani** [comment] 2016-11-04 08:08
http://localhost:8000/ in not working 
and route.php file can not find after installed

**Comment by radhika13sharma** [comment] 2017-10-25 20:08
hey why i am having two servers working at the same time.
i have no clue that i am working on one server local host 8000
and its showing result in local host 63342. i am trying atlot but not reaching any solution

**Comment by zhoubhin** [comment] 2017-11-03 06:20
@radhika13sharma Maybe you should close one of your servers first

**Comment by kopollo** [comment] 2017-11-04 16:32
You can try visit 8000 port number on webpage command line from [http://localhost.support/:8000](http://localhost.support/:8000)

**Comment by emile64** [comment] 2018-10-07 21:44
I tried to install symfony, at the last step, i cannot launch server listenning on : https;//127.0.0.1:8000

**Comment by johnef** [comment] 2020-01-23 09:50
I had the same issue here using wampserver and running Laravel framework and try to access http://localhost:8000 it gives error `server dial tcp4 127.0.0.1:80: connect: connection timed out` but when try to connect to http://127.0.0.1:8000 it works fine
