### ISSUE TITLE
Bower installs wrong version of Bootstrap

### ISSUE THREAD

**Issue by burak-tarhanli** [angular/angular-phonecat#383] opened 2016-11-10 11:30 UTC
In bower.json, the specified version for Bootstrap is "3.3.x", but Bower installs Bootstrap 4.0.0-alpha.4. As a result, the layout is getting broken because of wrong css.

**Comment by gkalpak** [comment] 2016-11-14 09:47
Unable to reproduce. I get Bootstrap version 3.3.7 (as expected). It would break half the web if `bower install bootstrap#3.3.x` install bootstrap v4.x :smiley:

I assume there is something else going on locally on your system. I am going to close this, but feel free to continue the discussion below. Happy to reopen if you can provide the steps to reproduce the problem from a fresh clone of `angular-phonecat`, with all dependencies up-to-date and clean npm/bower caches.

**Closed by gkalpak** 2016-11-14 09:47 UTC
